
```{r}
library(ggplot2)
library(gridExtra)
library(gplots)
library(RColorBrewer)
library(cowplot)
library(viridis)

Nspecies = 121
Nscenes = 1
```



```{r}
dat = read.csv(
    paste0("C:/Users/Gast/DART/user_data/simulations/Output_data/2_trees_test_lop_db/profiles_2d.csv"))
#dat$num_of_species = as.factor(dat$num_of_species)
dat$transm1 = 0.1*(dat$transm1 - 1)
dat$transm2 = 0.1*(dat$transm2 - 1)
dat$refl1 = 0.1*(dat$refl1 - 1)
dat$refl2 = 0.1*(dat$refl2 - 1)
#dat$species = as.factor(dat$species)
#levels(dat$species) = c("specie1", "specie2")

dat$transm_refl[dat$species == 0] = paste0(dat$transm1[dat$species == 0], "_", dat$refl1[dat$species == 0])
dat$transm_refl[dat$species == 1] = paste0(dat$transm2[dat$species == 1], "_", dat$refl2[dat$species == 1])
dat$species[dat$species == 0] = paste0(dat$transm1[dat$species == 0], "_", dat$refl1[dat$species == 0])
dat$species[dat$species == 1] = paste0(dat$transm2[dat$species == 1], "_", dat$refl2[dat$species == 1])

subdat_crown = as.data.frame(dat[dat$height_m != 1,])
subdat_crown$pos = subdat_crown$idSimulation
```

```{r}
dat$num_of_species[dat$num_of_species == 1] = 0
dat$num_of_species[(dat$refl1 == dat$refl2) & (dat$transm1 == dat$transm2)] = 1
```

```{r}
diff_betw_sp_in_mix_and_in_mon = function(subdat, Nscenes_loc = Nscenes, Nspecies_loc = Nspecies) {
 
  subdat_crown = as.data.frame(subdat[subdat$height_m != 1,])

  aggdat = aggregate(abs_mean ~ height_m + pos + num_of_species + scenetype + species, data = subdat_crown, FUN = "mean")
  aggdat = aggregate(abs_mean ~ pos + num_of_species + scenetype + species, data = aggdat, FUN = "sum")
  
  mix_tab = lapply(unique(aggdat$scenetype), function(SCTYPE) {
    res_tab = lapply(unique(aggdat$pos[as.numeric(aggdat$num_of_species) > 1]), function(POS) {

      av_mix = subset(aggdat, pos == POS & scenetype == SCTYPE)
      sps = unique(av_mix$species)
      av_mix_sp1 = av_mix$abs_mean[av_mix$species == sps[1]]
      av_mix_sp2 = av_mix$abs_mean[av_mix$species == sps[2]]
      av_mon_sp1 = subset(aggdat, species == sps[1] & scenetype == SCTYPE & num_of_species == 1)$abs_mean
      av_mon_sp2 = subset(aggdat, species == sps[2] & scenetype == SCTYPE & num_of_species == 1)$abs_mean

      one_mix = data.frame(cbind(c((av_mix_sp1 - av_mon_sp1)[1], (av_mix_sp2 - av_mon_sp2)[1]), 
                                 c(av_mon_sp1, av_mon_sp2),
                                 c(1, 0),
                                 rep(POS, 2) ))
      
      colnames(one_mix) = c("abs_mean", "mon_abs", "sp_a" ,"pos")
      one_mix$diff_mon = (av_mon_sp1 - av_mon_sp2)[1] ## difference in absorbtion of monocultures
      one_mix$diff_mix = (av_mix_sp1 - av_mix_sp2)[1] ## difference in absorbtion of mixtures
      one_mix$species = sps
      one_mix$name_species = paste0(sps[1], " + ", sps[2])
      
      return(one_mix)
    })
    res_tab = do.call(rbind.data.frame, res_tab)
    res_tab$scenetype = SCTYPE
    return(res_tab)
  })
  mix_tab = do.call(rbind.data.frame, mix_tab)
  
  return(mix_tab)
}
```


```{r}
subdat_crown$scenetype = 1
subdat_crown = unique(subdat_crown)
tab_2d = diff_betw_sp_in_mix_and_in_mon(subdat_crown, Nscenes_loc = Nscenes, Nspecies_loc = Nspecies)

```

```{r}
tab_2d = unique(tab_2d)
```

```{r fig.height=30, fig.width=14}
ggplot(data = tab_2d, 
       aes(x = pos, y = abs_mean, col = as.factor(species), group = as.factor(pos))) +
  geom_point(size = 2.5) + geom_hline(aes(yintercept = 0), col = "gray8") + geom_segment(aes(x=pos, xend=pos, y=0, yend=abs_mean )) +
  ylab("difference in mixtures minus monocultures")  + theme_bw() + xlab("different mixtures") + 
  ggtitle("type of background") + 
  #scale_color_viridis(option="inferno") +
  coord_flip() +
  #scale_color_brewer(palette = "Dark2") +
  #facet_grid(~scenetype, space = "free", scales = "free") + 
  #scale_y_continuous(breaks = seq(-1,0.15,0.05)) +
  #scale_y_continuous(breaks = seq(-1,1,0.2)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_blank(),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=7, fig.width=13}
ab_mixtab = tab_2d
ab_mixtab$diff_mon[ab_mixtab$sp_a == 0] = - ab_mixtab$diff_mon[ab_mixtab$sp_a == 0]
ggplot(data = ab_mixtab, 
       aes(x = diff_mon, y = abs_mean, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("gain_a")  + theme_bw() + xlab("abs_a - abs_b") + 
  ggtitle("type of background") + 
  #coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_x_continuous(breaks = seq(-1,1,0.1)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```
```{r}
c = 1/2
ab_mixtab$transm1 = as.numeric(sapply(ab_mixtab$name_species, function(x) strsplit(x, "_")[[1]][1]))
ab_mixtab$refl2 = as.numeric(sapply(ab_mixtab$name_species, function(x) strsplit(x, "_")[[1]][3]))

var_a = sapply(ab_mixtab$name_species, function(x) strsplit(x, "_")[[1]][2])
ab_mixtab$refl1 = as.numeric(sapply(var_a, function(x) strsplit(x, "\\ \\+\\ ")[[1]][1]))
ab_mixtab$transm2 = as.numeric(sapply(var_a, function(x) strsplit(x, "\\ \\+\\ ")[[1]][2]))
ab_mixtab$def_area = (ab_mixtab$refl1 == ab_mixtab$transm1)  & (ab_mixtab$refl2 == ab_mixtab$transm2)
ab_mixtab$my_formula = c*(1 - c)*ab_mixtab$diff_mix/(1 - ab_mixtab$transm1)
```

```{r fig.height=7, fig.width=13, message=FALSE, warning=FALSE, paged.print=FALSE}
ab_mixtab = na.omit(ab_mixtab)
ggplot(data = ab_mixtab[ab_mixtab$def_area,], 
       aes(x = my_formula, y = abs_mean, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("gain_a")  + theme_bw() + xlab("my_formula") + 
  ggtitle("type of background") + 
  #coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_x_continuous(breaks = seq(-1,1,0.1)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```


```{r fig.height=7, fig.width=8, message=FALSE, warning=FALSE}
ab_mixtab = tab_2d
ab_mixtab$diff_mon[ab_mixtab$sp_a == 0] = - ab_mixtab$diff_mon[ab_mixtab$sp_a == 0]
ab_mixtab$refl1 = subdat_crown$refl1[match(ab_mixtab$pos, subdat_crown$pos)]
ab_mixtab$refl2 = subdat_crown$refl2[match(ab_mixtab$pos, subdat_crown$pos)]
ab_mixtab$transm1 = subdat_crown$transm1[match(ab_mixtab$pos, subdat_crown$pos)]
ab_mixtab$transm2 = subdat_crown$transm2[match(ab_mixtab$pos, subdat_crown$pos)]
ab_mixtab$a1_a2 = as.factor(round(ab_mixtab$refl1 - ab_mixtab$refl2 + ab_mixtab$transm1 - ab_mixtab$transm2, 2))
ggplot(data = ab_mixtab, 
       aes(x = diff_mix, y = abs_mean, col = a1_a2, group = as.factor(pos)) ) +
  geom_point() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("gain_a") + xlab("abs_mix_a - abs_mix_b") + 
  ggtitle("The butterfly") + 
  theme_bw() +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=8, fig.width=13}
ab_mixtab = tab_2d
ab_mixtab$diff_mon[ab_mixtab$sp_a == 0] = - ab_mixtab$diff_mon[ab_mixtab$sp_a == 0]
ggplot(data = ab_mixtab, 
       aes(x = diff_mix, y = abs_mean, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("gain_a")  + theme_bw() + xlab("abs_mix_a - abs_mix_b") + 
  ggtitle("the butterfly") + 
  #coord_flip() +
  #facet_grid(~scenetype, space = "free", scales = "free") + 
  #scale_x_continuous(breaks = seq(-1,1,0.1)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=7, fig.width=13}

ggplot(data = ab_mixtab, 
       aes(x = mon_abs*diff_mon, y = abs_mean, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("gain_a")  + theme_bw() + xlab("abs_a - abs_b") + 
  ggtitle("the flight of butterfly") + 

  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=8, fig.width=10}

ggplot(data = ab_mixtab, 
       aes(x = diff_mix, y = mon_abs*diff_mon, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("abs_a*(abs_a - abs_b)")  + theme_bw() + xlab("diff_mix") + 
  ggtitle("the flight of butterfly") + 

  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=8, fig.width=8}

ggplot(data = ab_mixtab, 
       aes(x = diff_mix, y = mon_abs*diff_mon, col = a1_a2, group = as.factor(pos)) ) +
  geom_point() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("abs_a*(abs_a - abs_b)")  + theme_bw() + xlab("diff_mix") + 
  ggtitle("the flight of butterfly") + 

  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=10, fig.width=13}

ggplot(data = ab_mixtab, 
       aes(x = diff_mix, y = diff_mon, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("diff_mon")  + theme_bw() + xlab("diff_mix") + 
  ggtitle("the butterfly") + 

  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r}

subdat_crown$pos = subdat_crown$idSimulation
aggdat = aggregate(abs_mean ~ height_m + pos + transm1 + transm2 + refl1 + refl2 + num_of_species, 
                   data = subdat_crown, FUN = "mean")
res_tab = lapply(unique(aggdat$pos[as.numeric(aggdat$num_of_species) > 1]), function(POS) {

  av_mixture = subset(aggdat, pos == POS, abs_mean)

  abs_of_monocultures = lapply(unique(subdat_crown$species[subdat_crown$pos == POS]), function(x) {
    position_of_mon = subdat_crown$pos[subdat_crown$species == x & 
                                         subdat_crown$num_of_species == 1][1]
    res = subset(aggdat, pos == position_of_mon, select = abs_mean)
    return(res)
  })
    
  av_monocultures = apply(do.call(rbind.data.frame, list(abs_of_monocultures)), 1, mean)
  
  
  one_mix = data.frame( (av_mixture[,1] - av_monocultures), c(1:nrow(av_mixture)), rep(POS, nrow(av_mixture)))
  colnames(one_mix) = c("abs_mean", "height_m", "pos")
  
  one_mix$diff_sum = rep(round(sum(one_mix$abs_mean), 7), nrow(one_mix))
  one_mix$num_of_species = rep(aggdat$num_of_species[aggdat$pos == POS][1], nrow(one_mix))
  one_mix$transm1 = rep(aggdat$transm1[aggdat$pos == POS][1], nrow(one_mix))
  one_mix$transm2 = rep(aggdat$transm2[aggdat$pos == POS][1], nrow(one_mix))
  one_mix$refl1 = rep(aggdat$refl1[aggdat$pos == POS][1], nrow(one_mix))
  one_mix$refl2 = rep(aggdat$refl2[aggdat$pos == POS][1], nrow(one_mix))
  
  return(one_mix)
})
res_tab = do.call(rbind.data.frame, res_tab)
```

```{r fig.height=8, fig.width=11}
ggplot(data = res_tab, 
       aes(x = height_m, y = abs_mean, col = diff_sum, group = as.factor(pos))) +
  geom_line(size = 0.05) +
  ylab("proportion of absorbed light")  + theme_bw() + xlab("height, m") + 
  ggtitle("Comparison of mixtures and monocultures") + 
  scale_color_gradient(low="darkblue", high="red") +
  #scale_color_manual(labels = c(paste0("Average of mixture ", mix_sum), paste0("Average of monocultures ", mon_sum)), 
  #                   values = my_palette) +
  coord_flip() +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```


```{r fig.height=5, fig.width=8}
res_tab$min_transm = as.factor(pmin(res_tab$transm1, res_tab$transm2))
res_tab$transm_refl = dat$species[match(res_tab$pos,dat$idSimulation)]
ggplot(data = res_tab[res_tab$refl1 == 0.4 & res_tab$refl2 == 0.4,], 
       aes(x = abs(transm2 - transm1), y = diff_sum, col = min_transm, group = as.factor(pos))) +
  geom_point(size = 3) + #geom_line(aes(group = as.factor(transm1)), size = 0.8) +
  ylab("difference in abs mixtures - monocultures")  + theme_bw() + xlab("difference in absorbance between 2 species") + 
  #ggtitle("Comparison of mixtures and monocultures") + 
  #scale_color_brewer(palette = "Spectral") +
  #ylim(c(0, 0.023)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), #panel.grid.minor = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=5, fig.width=8}
ggplot(data = res_tab[res_tab$transm1 == 0.4 & res_tab$transm2 == 0.4,], 
       aes(x = abs(refl2 - refl1), y = diff_sum, col = as.factor(refl1), group = as.factor(pos))) +
  geom_point(size = 2) + #geom_line(aes(group = as.factor(transm1)), size = 0.8) +
  ylab("difference in abs mixtures - monocultures")  + theme_bw() + xlab("difference in absorbance between 2 species") + 
  #ggtitle("Comparison of mixtures and monocultures") + 
  #scale_color_brewer(palette = "Spectral") +

  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```
```{r}
summary(1 - 0.1*as.numeric(subdat_crown$num_of_species))
```
```{r fig.height=8, fig.width=12}
#my_palette = brewer.pal(9, "YlGn")[9:1]
aggdat = aggregate(albedo ~ idSimulation + transm1 + transm2 + refl1 + refl2 + species + num_of_species + transm_refl, 
                   data = subdat_crown, FUN = "mean")
aggdat$sp1 =  paste0(aggdat$transm1, "_", aggdat$refl1)
aggdat$sp2 =  paste0(aggdat$transm2, "_", aggdat$refl2)
aggdat = aggdat[aggdat$num_of_species == 2,]

vector_a = aggdat$sp1
vector_b = aggdat$sp2

albmat = sapply(unique(vector_a), function (a) 
  sapply(unique(vector_b), function(b) 
    mean( dat$albedo[vector_a == a & vector_b== b])))

heatmap.2(t(albmat),margins=c(5,5), scale="none", labCol = unique(vector_b),
          labRow = unique(vector_a),
          dendrogram="none",  trace="none", xlab = "Specie2", 
          ylab = "Specie1", main = "Albedo", density.info="none", Colv = NA, Rowv = NA)
#,col=my_palette)
```
```{r fig.height=8, fig.width=12}

aggdat = aggregate(diff_sum ~ pos + transm1 + transm2 + refl1 + refl2, 
                   data = res_tab, FUN = "mean")
aggdat$sp1 =  round( abs(aggdat$transm1 - aggdat$transm2) , 2)
#aggdat$sp1 =  round( abs(aggdat$refl1 - aggdat$refl2) , 2)
aggdat$sp2 =  round( abs(aggdat$transm1 - aggdat$transm2 + aggdat$refl1 - aggdat$refl2) , 2)

vector_a = aggdat$sp1
vector_b = aggdat$sp2

albmat = sapply(sort(unique(vector_a)), function (a) 
  sapply(sort(unique(vector_b)), function(b) 
    mean( aggdat$diff_sum[vector_a == a & vector_b== b])))

my_palette = brewer.pal(7,"Oranges")
my_palette=colorRampPalette(my_palette)(100)
heatmap.2(t(albmat),margins=c(5,5), scale="none", labCol = sort(unique(vector_b)),
          labRow = sort(unique(vector_a)),
          dendrogram="none",  trace="none", xlab = "Difference in absorptance", 
          ylab = "Difference in transmittance", main = "Diff_sum", density.info="none", Colv = NA, Rowv = NA,
          col = my_palette, symm=F,symkey=F,symbreaks=F)

```

```{r}
library(plotly)
p <- plot_ly(z = ~t(albmat)) %>% add_surface() %>%
  layout(
    title = "Difference in absorptance between mixtures and monocultures",
    scene = list(
      xaxis = list(title = "Difference in absorptance"),
      yaxis = list(title = "Difference in transmittance"),
      zaxis = list(title = "Difference")
    ))
p
```

```{r}
library(caret)
set.seed(123)
training.samples <- sample(2,length(aggdat), replace = T) - 1
train.data  <- aggdat[training.samples, ]
test.data <- aggdat[-training.samples, ]
# Build the model
model <- lm(diff_sum ~ transm1 + transm2 + refl1 + refl2, data = aggdat)
# Summarize the model
summary(model)
# Make predictions
predictions <- predict(model, test.data)
# Model performance
# (a) Prediction error, RMSE
RMSE(predictions, test.data$diff_sum)
# (b) R-square
R2(predictions, test.data$diff_sum)

```

```{r}
mod = lm(diff_sum ~ 
           I(refl1*transm1) + I(refl1*transm2) + 
           I(refl2*transm1) + I(refl2*transm2),
         data = res_tab)
summary(mod)
```


```{r}
library(nnet)
aggdat$abs1 = 1 - aggdat$transm1 - aggdat$refl1
aggdat$abs2 = 1 - aggdat$transm2 - aggdat$refl2
mod = lm(diff_sum ~
           I(abs1*transm1*refl1) + I(abs1*transm2*refl2) + 
           I(abs2*transm1*refl1) + I(abs2*transm2*refl2) +
           
           I(abs1*transm1*refl1**2) + I(abs1*transm2*refl2**2) +
           I(abs2*transm1*refl1**2) + I(abs2*transm2*refl2**2) +
           
           I(abs1*transm1**2*refl1) + I(abs1*transm2**2*refl2) +
           I(abs2*transm1**2*refl1) + I(abs2*transm2**2*refl2) +
           
           #I(abs1*transm2**2*refl1**2) + I(abs2*transm1**2*refl2**2) +
           
           
           I(abs1*refl1**2) + I(abs2*refl2**2) +
           I(abs1*refl2**2) + I(abs2*refl1**2) +
           I(abs1*transm2**2) + I(abs2*transm1**2) +
           I(abs1*transm1**2) + I(abs2*transm2**2) +
           
           #I(abs1*refl1*refl2) + I(abs2*refl1*refl2) +
           #I(abs1*transm1*transm2**2*refl1) + I(abs2*transm1**2*transm2*refl2) +
           #I(abs1*refl1*refl2**2) + I(abs2*refl2*refl1**2) +
           
           I(abs1*transm1**3) + I(abs2*transm2**3) +
           I(abs1*transm2**3) + I(abs2*transm1**3) +
           I(abs1*refl1**3) + I(abs2*refl2**3) +
           I(abs1*refl2**3) + I(abs2*refl1**3),
         data = aggdat) 

summary(mod)
```


```{r}
library(plotly)
p <- plot_ly(z = ~t(albmat)) %>% add_surface() %>%
  layout(
    title = "Difference in absorptance between mixtures and monocultures",
    scene = list(
      xaxis = list(title = "Difference in absorptance"),
      yaxis = list(title = "Difference in transmittance"),
      zaxis = list(title = "Difference")
    ))
p
```
$$\sum_{i=1}^n X_i$$

```{r fig.height=8, fig.width=12}

aggdat = aggregate(diff_sum ~ pos + transm1 + transm2 + refl1 + refl2, 
                   data = res_tab, FUN = "mean")
aggdat$sp1 =  round( abs(aggdat$transm1 - aggdat$transm2) , 2)
#aggdat$sp1 =  round( abs(aggdat$refl1 - aggdat$refl2) , 2)
aggdat$sp2 =  round( abs(aggdat$transm1 - aggdat$transm2 + aggdat$refl1 - aggdat$refl2) , 2)
#aggdat$sp1 =  round( abs(1 - aggdat$refl1 + aggdat$transm1) , 1)
#aggdat$sp2 =  round( abs(1 - aggdat$refl2 + aggdat$transm2) , 1)

vector_a = aggdat$sp1
vector_b = aggdat$sp2

albmat = sapply(sort(unique(vector_a)), function (a) 
  sapply(sort(unique(vector_b)), function(b) 
    mean( aggdat$diff_sum[vector_a == a & vector_b== b])))

analyt_albmat = sapply(sort(unique(vector_a)), function (a) 
  sapply(sort(unique(vector_b)), function(b) 
    mean( aggdat$diff_sum[vector_a == a & vector_b== b])))

my_palette = brewer.pal(7,"Oranges")
my_palette=colorRampPalette(my_palette)(100)
heatmap.2(t(albmat),margins=c(5,5), scale="none", labCol = sort(unique(vector_b)),
          labRow = sort(unique(vector_a)),
          dendrogram="none",  trace="none", xlab = "Difference in absorptance", 
          ylab = "Difference in transmittance", main = "Diff_sum", density.info="none", Colv = NA, Rowv = NA,
          col = my_palette, symm=F,symkey=F,symbreaks=F)

library(plotly)
p <- plot_ly(z = ~t(albmat)) %>% add_surface() %>%
  layout(
    title = "Difference in absorptance between mixtures and monocultures",
    scene = list(
      xaxis = list(title = "Difference in absorptance"),
      yaxis = list(title = "Difference in transmittance"),
      zaxis = list(title = "Albedo")
    ))
p


```


```{r fig.height=8, fig.width=12}

aggdat = aggregate(diff_sum ~ pos + transm1 + transm2 + refl1 + refl2, 
                   data = res_tab, FUN = "mean")
aggdat$sp1 =  round( abs(aggdat$transm1 + aggdat$transm2) , 2)
#aggdat$sp2 =  round( abs(aggdat$refl1 - aggdat$refl2) , 2)
aggdat$sp2 =  round( abs(aggdat$transm1 - aggdat$transm2 + aggdat$refl1 - aggdat$refl2) , 2)

vector_a = aggdat$sp1
vector_b = aggdat$sp2

albmat = sapply(sort(unique(vector_a)), function (a) 
  sapply(sort(unique(vector_b)), function(b) 
    mean( aggdat$diff_sum[vector_a == a & vector_b== b])))

analyt_albmat = sapply(sort(unique(vector_a)), function (a) 
  sapply(sort(unique(vector_b)), function(b) 
    mean( aggdat$diff_sum[vector_a == a & vector_b== b])))

my_palette = brewer.pal(7,"Oranges")
my_palette=colorRampPalette(my_palette)(100)
heatmap.2(t(albmat),margins=c(5,5), scale="none", labCol = sort(unique(vector_b)),
          labRow = sort(unique(vector_a)),
          dendrogram="none",  trace="none", xlab = "Difference in absorptance", 
          ylab = "Difference in transmittance", main = "Diff_sum", density.info="none", Colv = NA, Rowv = NA,
          col = my_palette, symm=F,symkey=F,symbreaks=F)

```
```{r}
library(plotly)
p <- plot_ly(z = ~t(albmat)) %>% add_surface() %>%
  layout(
    title = "Difference in absorptance between mixtures and monocultures",
    scene = list(
      xaxis = list(title = "Difference in absorptance"),
      yaxis = list(title = "Difference in transmittance"),
      zaxis = list(title = "Albedo")
    ))
p
```


```{r}
dalbmat = as.data.frame(albmat)
ggplot(data = dalbmat, 
       aes(x = c(0:10)/10, y = V1, col = as.factor(V1))) + 
  geom_point() +
  ylab("proportion of absorbed light")  + theme_bw() + xlab("height, m") + ggtitle("Species") +
  scale_color_brewer(palette="Spectral") + scale_fill_brewer(palette="Spectral")  + coord_flip() +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```


```{r fig.height=8, fig.width=12}

aggdat = aggregate(albedo ~ idSimulation + transm1 + transm2 + refl1 + refl2 + species + num_of_species + transm_refl, 
                   data = subdat_crown, FUN = "mean")
aggdat$sp1 =  round( abs(aggdat$transm1 - aggdat$transm2) , 2)
aggdat$sp2 =  round( abs(aggdat$refl1 - aggdat$refl2) , 2)
#aggdat$sp2 =  round( abs(aggdat$transm1 - aggdat$transm2 + aggdat$refl1 - aggdat$refl2) , 2)

vector_a = aggdat$sp1
vector_b = aggdat$sp2

albmat = sapply(sort(unique(vector_a)), function (a) 
  sapply(sort(unique(vector_b)), function(b) 
    mean( aggdat$albedo[vector_a == a & vector_b== b])))

my_palette = brewer.pal(7,"Oranges")[7:1]
my_palette=colorRampPalette(my_palette)(100)
heatmap.2(t(albmat),margins=c(5,5), scale="none", labCol = sort(unique(vector_b)),
          labRow = sort(unique(vector_a)),
          dendrogram="none",  trace="none", xlab = "Difference in absorptance", 
          ylab = "Difference in transmittance", main = "Albedo", density.info="none", Colv = NA, Rowv = NA,
          col = my_palette, symm=F,symkey=F,symbreaks=F)

```

```{r}
library(plotly)
p <- plot_ly(z = ~t(albmat)) %>% add_surface() %>%
  layout(
    title = "Difference in absorptance between mixtures and monocultures",
    scene = list(
      xaxis = list(title = "Difference in absorptance"),
      yaxis = list(title = "Difference in transmittance"),
      zaxis = list(title = "Albedo")
    ))
p
```



```{r}
aggdat$diff_sum[vector_a == 0.7 & vector_b== 0.7]
mean( aggdat$diff_sum[vector_a == 0.7 & vector_b== 0.1])
min(albmat)
```

```{r fig.height=8, fig.width=12}

aggdat = aggregate(albedo ~ idSimulation + transm1 + transm2 + refl1 + refl2 + species + num_of_species + transm_refl, 
                   data = subdat_crown, FUN = "mean")
aggdat$sp1 =  round( abs(aggdat$transm1 - aggdat$transm2) , 2)
aggdat$sp2 =  round( abs(aggdat$refl1 - aggdat$refl2) , 2)
aggdat = aggdat[aggdat$num_of_species == 2,]

vector_a = aggdat$sp1
vector_b = aggdat$sp2

albmat = sapply(sort(unique(vector_a)), function (a) 
  sapply(sort(unique(vector_b)), function(b) 
    mean( aggdat$albedo[vector_a == a & vector_b== b])))

my_palette = brewer.pal(7,"Oranges")[7:1]
my_palette=colorRampPalette(my_palette)(100)
heatmap.2(t(albmat),margins=c(5,5), scale="none", labCol = sort(unique(vector_b)),
          labRow = sort(unique(vector_a)),
          dendrogram="none",  trace="none", xlab = "Difference in reflectance", 
          ylab = "Difference in transmittance", main = "Albedo", density.info="none", Colv = NA, Rowv = NA,
          col = my_palette)

```

```{r}
library(plotly)
p <- plot_ly(z = ~t(albmat)) %>% add_surface() %>%
  layout(
    title = "Difference in absorptance between mixtures and monocultures",
    scene = list(
      xaxis = list(title = "Difference in absorptance"),
      yaxis = list(title = "Difference in transmittance"),
      zaxis = list(title = "Albedo")
    ))
p
```

```{r fig.height=8, fig.width=12}

aggdat = aggregate(abs_mean ~ idSimulation + transm1 + transm2 + refl1 + refl2 + species + num_of_species + transm_refl, 
                   data = subdat_crown, FUN = "sum")
#aggdat$sp1 =  round( abs(aggdat$transm1 - aggdat$transm2) , 2)
#aggdat$sp2 =  round( abs(aggdat$refl1 - aggdat$refl2) , 2)
aggdat$sp1 =  round( abs(1 - aggdat$refl1 - aggdat$transm1) , 1)
aggdat$sp2 =  round( abs(1 - aggdat$refl2 - aggdat$transm2) , 1)
#aggdat$sp2 =  round( abs(aggdat$transm1 - aggdat$transm2 + aggdat$refl1 - aggdat$refl2) , 2)
aggdat = aggdat[aggdat$num_of_species == 2,]

vector_a = aggdat$sp1
vector_b = aggdat$sp2

albmat = sapply(sort(unique(vector_a)), function (a) 
  sapply(sort(unique(vector_b)), function(b) 
    mean( aggdat$abs_mean[vector_a == a & vector_b== b])))

my_palette = brewer.pal(7,"Oranges")
my_palette=colorRampPalette(my_palette)(100)

heatmap.2(t(albmat),margins=c(5,5), scale="none", labCol = sort(unique(vector_b)),
          labRow = sort(unique(vector_a)),
          dendrogram="none",  trace="none", xlab = "Difference in reflectance", 
          ylab = "Difference in transmittance", main = "Absorbptance", density.info="none", Colv = NA, Rowv = NA,
          col = my_palette)

```
```{r}
library(plotly)
p <- plot_ly(z = ~t(albmat)) %>% add_surface() %>%
  layout(
    title = "Difference in absorptance between mixtures and monocultures",
    scene = list(
      xaxis = list(title = "Difference in absorptance"),
      yaxis = list(title = "Difference in transmittance"),
      zaxis = list(title = "Albedo")
    ))
p
```


```{r fig.height=7, fig.width=12}
ggplot(data = subdat_crown, 
       aes(x = height_m, y = abs_mean, col = num_of_species)) + 
  #stat_summary(aes(col = num_of_species), fun.y = 'mean', geom = 'line', size = 1.4) +
  #stat_summary(aes(fill = num_of_species), fun.data = 'mean_sdl', geom = 'ribbon', alpha = 0.2, 
  #             fun.args = list(mult = 1)) +
  geom_line(aes(group = idSimulation)) +
  scale_y_continuous(breaks = seq(0,0.15,0.05)) +
  facet_grid(~species, space = "free", scales = "free") +  
  #geom_text(data  = ann_text_first, mapping = aes(x = -Inf, y = -Inf, label = label),
  #          hjust = -0.5, vjust   = -25, show.legend = FALSE, size = 4.5) +
  #geom_text(data  = ann_text_last, mapping = aes(x = -Inf, y = -Inf, label = label),
  #          hjust = -0.5, vjust   = -23, show.legend = FALSE, size = 4.5) +
  #geom_text(data = ann_text,label = as.character(ann_text$label), show.legend = FALSE) +
  
  ylab("proportion of absorbed light")  + theme_bw() + xlab("height, m") + ggtitle("Species") +
  scale_color_brewer(palette="Dark2") + scale_fill_brewer(palette="Spectral")  + coord_flip() +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r}

aggdat = aggregate(abs_mean ~ idSimulation + num_of_species + transm1 + transm2 + species, data = subdat, FUN = "sum")
head(aggdat[aggdat$species == 0,], 30)
```


```{r fig.height=8, fig.width=9}
ggplot(data = res_tab[res_tab$transm1 == 0.1,], 
       aes(x = height_m, y = abs_mean, col = transm2, group = as.factor(pos))) +
  geom_line(size = 1) +
  ylab("proportion of absorbed light")  + theme_bw() + xlab("height, m") + 
  ggtitle("Comparison of mixtures and monocultures") + 
  scale_color_gradient(low="darkblue", high="red") +
  #scale_color_manual(labels = c(paste0("Average of mixture ", mix_sum), paste0("Average of monocultures ", mon_sum)), 
  #                   values = my_palette) +
  coord_flip() +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r}
aggdat = aggregate(albedo ~ idSimulation + num_of_species + transm1 + transm2, data = subdat, FUN = "mean")
unique(res_tab$pos[res_tab$diff_sum < 0.05])
```

```{r}
ggplot(aggdat, aes(x = transm1, y = albedo, color = as.factor(transm2))) + 
  geom_point(size = 2, alpha = 1) + 
  xlab("transitance 1") + ylab("albedo") + theme_bw() + 
  scale_color_brewer(palette="Dark2") +
 theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```


```{r}
aggdat[aggdat$idSimulation %in% unique(res_tab$pos[res_tab$diff_sum > 0.015]),]
aggdat[aggdat$idSimulation %in% unique(res_tab$pos[res_tab$diff_sum < 0.005]),]
```

```{r}
ggplot(aggdat[aggdat$num_of_species == 1 & aggdat$transm1 == 0,], aes(x = transm2, y = albedo, color = as.factor(transm2))) + 
  geom_point(size = 2, alpha = 1) + 
  xlab("transitance 2") + ylab("albedo") + theme_bw() + 
  scale_color_brewer(palette="Dark2") +
 theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r}
aggdat[aggdat$transm1 == 0.2 & aggdat$transm2 == 0.4,]
```


```{r fig.height=7, fig.width=12}
cumsumm = cumsum(unlist(sapply(c(1:Nspecies), function(x) choose(Nspecies, x))))

diffs = lapply(c(2:Nspecies), function(k) sapply(c(1:choose(Nspecies, k)), function(i) 
  aggdat$albedo[i+cumsumm[k-1]] - sum(aggdat$albedo[combn(Nspecies, k)[,i]])/k))

diffs = as.data.frame(cbind(unlist(diffs), aggdat$num_of_species[-c(1:Nspecies)]))
colnames(diffs) = c("differences", "num_of_species")
diffs$num_of_species = as.factor(diffs$num_of_species)

ggplot(diffs, aes(x = num_of_species, y = differences, col = num_of_species)) + 
  geom_point(size = 2) + geom_hline(yintercept = 0) + 
  xlab("number of species") + ylab("differences with average of monocultures") + theme_bw() + 
  scale_color_brewer(palette="Dark2") +
 theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))


```


## Leaf optical properties

```{r fig.height=7, fig.width=12}
subdat = read_profiles(param, trait = "lop")

sp_of_interest = subset(subdat, height_m != 1, select = c("num_of_species", "species", "pos", "scenetype", "height_m", "abs_mean"))

sp_of_interest$scenetype = as.factor(sp_of_interest$scenetype)
levels(sp_of_interest$scenetype) = c("white", "black", "natural")

whbl_subdat = merge(sp_of_interest[sp_of_interest$scenetype == "white",], 
                    sp_of_interest[sp_of_interest$scenetype == "black",], 
                      by = c("num_of_species", "species", "pos", "height_m"))
whbl_subdat$abs_mean = whbl_subdat$abs_mean.x - whbl_subdat$abs_mean.y
whbl_subdat$scenetype = "white - black"
whbl_subdat = subset(whbl_subdat, select = c("num_of_species", "species", "pos", "scenetype", "height_m", "abs_mean"))

sp_of_interest = as.data.frame(rbind(sp_of_interest, whbl_subdat))
sp_of_interest$scenetype = factor(sp_of_interest$scenetype,c("white", "black", "white - black", "natural"))
mix_tab = diff_betw_mix_and_av_of_mon(sp_of_interest)


sp_of_interest$pos = as.factor(sp_of_interest$pos)
levels(sp_of_interest$pos) = c("mon", "mon", "mix")

ggplot(data = sp_of_interest, 
       aes(x = height_m, y = abs_mean, col = interaction(pos, species), group = interaction(pos, species))) +
  geom_line(size = 1.2) +
  ylab("proportion of absorbed light")  + theme_bw() + xlab("height, m") + 
  ggtitle("type of background") + 
  scale_color_brewer(palette = "Paired", direction = -1) +
  coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_y_continuous(breaks = seq(-0.1,0.2,0.05)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))

```
```{r fig.height=7, fig.width=12}
subdat = aggregate(abs_mean ~ num_of_species + pos + species + scenetype, data = sp_of_interest, FUN = "sum")
ggplot(subdat, aes(x = species, y = abs_mean, fill = interaction(pos, species))) + geom_bar(stat="identity", position="dodge") +
  ylab("proportion of light")  + theme_bw() + xlab("height, m") + ggtitle("Light, absorbed by each specie") +
  scale_color_brewer(palette="Paired") + scale_fill_brewer(palette="Paired") +
  coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_y_continuous(breaks = seq(0,1,0.25)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```


### Difference in absorptance

```{r fig.height=7, fig.width=12}
ggplot(data = mix_tab, 
       aes(x = height_m, y = abs_mean, col = diff_sum, group = as.factor(pos))) +
  geom_line(size = 1) +
  ylab("proportion of absorbed light")  + theme_bw() + xlab("height, m") + 
  ggtitle("type of background") + 
  scale_color_viridis(option="inferno") +
  coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  #scale_y_continuous(breaks = seq(0,0.15,0.002)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=7, fig.width=12}
subdat = read_profiles(trait = "lop")
mix_tab = diff_betw_mix_and_av_of_mon(subdat)

ggplot(data = mix_tab, 
       aes(x = height_m, y = abs_mean, col = diff_sum, group = as.factor(pos))) +
  geom_line(size = 1) +
  ylab("proportion of absorbed light")  + theme_bw() + xlab("height, m") + 
  ggtitle("type of background") + 
  scale_color_viridis(option="inferno") +
  coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_y_continuous(breaks = seq(0,0.15,0.002)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))

```
