
---
title: "Regression of differences to difference in monocultures"
author: "Elena Plekhanova"
date: "`r format(Sys.time(), '%B %e, %Y')`"
output:
  html_notebook:
    code_folding: hide
  pdf_document: default
fontsize: 16pt
---


```{r}
library(ggplot2)
library(gridExtra)
library(viridis)

diff_betw_sp_in_mix_and_in_mon = function(subdat, Nscenes_loc = Nscenes, Nspecies_loc = Nspecies) {
 
  subdat_crown = as.data.frame(subdat[subdat$height_m != 1,])

  aggdat = aggregate(abs_mean ~ height_m + pos + num_of_species + scenetype + species, data = subdat_crown, FUN = "mean")
  aggdat = aggregate(abs_mean ~ pos + num_of_species + scenetype + species, data = aggdat, FUN = "sum")
  
  mix_tab = lapply(unique(aggdat$scenetype), function(SCTYPE) {
    res_tab = lapply(unique(aggdat$pos[as.numeric(aggdat$num_of_species) > 1]), function(POS) {

      av_mix = subset(aggdat, pos == POS & scenetype == SCTYPE)
      sps = unique(av_mix$species)
      av_mix_sp1 = av_mix$abs_mean[av_mix$species == sps[1]]
      av_mix_sp2 = av_mix$abs_mean[av_mix$species == sps[2]]
      av_mon_sp1 = subset(aggdat, species == sps[1] & scenetype == SCTYPE & num_of_species == 1)$abs_mean
      av_mon_sp2 = subset(aggdat, species == sps[2] & scenetype == SCTYPE & num_of_species == 1)$abs_mean

      one_mix = data.frame(cbind(c((av_mix_sp1 - av_mon_sp1)[1], (av_mix_sp2 - av_mon_sp2)[1]), 
                                 c(av_mon_sp1, av_mon_sp2),
                                 c(1, 0),
                                 rep(POS, 2) ))
      
      colnames(one_mix) = c("abs_mean", "mon_abs", "sp_a" ,"pos")
      one_mix$diff_mon = (av_mon_sp1 - av_mon_sp2)[1] ## difference in absorbtion of monocultures
      one_mix$diff_mix = (av_mix_sp1 - av_mix_sp2)[1] ## difference in absorbtion of mixtures
      one_mix$gain_mix = (av_mix_sp1 - av_mon_sp1)[1] + (av_mix_sp2 - av_mon_sp2)[1] ## difference in absorbtion of mixtures
      one_mix$species = sps
      one_mix$name_species = paste0(sps[1], " + ", sps[2])
      
      return(one_mix)
    })
    res_tab = do.call(rbind.data.frame, res_tab)
    res_tab$scenetype = SCTYPE
    return(res_tab)
  })
  mix_tab = do.call(rbind.data.frame, mix_tab)
  
  return(mix_tab)
}


read_profiles = function(trait_loc = trait, WAVE_RANGE_loc = WAVE_RANGE, sun_angle_30_loc = sun_angle_30) {
  
  angle = "90"
  if (sun_angle_30_loc) angle = "30"
  
  dat = read.csv(
    paste0("./Data_for_figures/",trait_loc,"6_profiles_", angle, ".csv"))
  
  dat$num_of_species = as.factor(dat$num_of_species)
  dat$species = as.factor(dat$species)
  if (trait_loc == "lad") {
    levels(dat$species) = c("Spherical", "Uniform", "Vertical", "Horizontal", "Ellipsoidal", "Extremophile")
  } else
    levels(dat$species) = c( "beech", "birch", "elm", "eucalyptus", "spruce", "aspen")
  
  subdat = dat[dat$band == WAVE_RANGE_loc,]
}

myprettyoptions = theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(),
        plot.title = element_text(size=12, hjust = 0.5),
        axis.title.x = element_text(size=12), axis.text.x  = element_text(size=10),
        axis.title.y = element_text(size=12), axis.text.y  = element_text(size=10),
        strip.text.x = element_text(size = 10), strip.text.y = element_text(size = 12),
        legend.text = element_text(size=8), legend.title = element_text(size=8), title = element_text(size=10))
```



```{r}
Ncomb = 63
Nscenes = 3
Nspecies = 6
WAVE_RANGE = "VIS"
trait = "lop"
sun_angle_30 = F
```


```{r}
cumsumm = cumsum(unlist(sapply(c(1:Nspecies), function(x) choose(Nspecies, x))))
the_list_of_comb = sapply(c(1:Nspecies), function(k) sapply(c(1:choose(Nspecies, k)), function(i) combn(Nspecies, k)[,i]))
the_list_of_sp = unlist(sapply(c(2:Nspecies), function(j) { x = the_list_of_comb[[j]]
  res = split(x, rep(1:ncol(x), each = nrow(x)))
  return(res)}), recursive = FALSE)
the_list_of_sp = append(sapply(c(1:Nspecies), function(x) list(x)), the_list_of_sp)
names(the_list_of_sp) = c(1:63)

```


## Leaf optical properties


```{r fig.height=7, fig.width=12}
subdat = read_profiles(trait = "lop")
#sp_of_interest = subset(subdat, height_m != 1 & pos %in% c(3,4,16))
sp_of_interest = subset(subdat, height_m != 1 & num_of_species %in% c(1,2), select = c("num_of_species", "species", "pos", "scenetype", "height_m", "abs_mean"))


sp_of_interest$scenetype = as.factor(sp_of_interest$scenetype)
levels(sp_of_interest$scenetype) = c("white", "black", "natural")


whbl_subdat = merge(sp_of_interest[sp_of_interest$scenetype == "white",], 
                    sp_of_interest[sp_of_interest$scenetype == "black",], 
                      by = c("num_of_species", "species", "pos", "height_m"))
whbl_subdat$abs_mean = whbl_subdat$abs_mean.x - whbl_subdat$abs_mean.y
whbl_subdat$scenetype = "white - black"
whbl_subdat = subset(whbl_subdat, select = c("num_of_species", "species", "pos", "scenetype", "height_m", "abs_mean"))

sp_of_interest = as.data.frame(rbind(sp_of_interest, whbl_subdat))
sp_of_interest$scenetype = factor(sp_of_interest$scenetype,c("white", "black", "white - black", "natural"))

sp_of_interest$pos = as.factor(sp_of_interest$pos)
#levels(sp_of_interest$pos) = c("mon", "mon", "mix")

ggplot(data = sp_of_interest, 
       aes(x = height_m, y = abs_mean, col = interaction(num_of_species, species), group = interaction(pos, species))) +
  geom_line(size = 1.2) +
  ylab("proportion of absorbed light")  + theme_bw() + xlab("height, m") + 
  ggtitle("type of background") + 
  scale_color_brewer(palette = "Paired",direction=-1, name = "Mon/Mix.Species") +
  coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_y_continuous(breaks = seq(0,0.14,0.05)) +
  myprettyoptions
```

```{r fig.height=4, fig.width=2.3}
sp_of_interest = subset(subdat, height_m != 1 & pos %in% c(1,3,8) & num_of_species %in% c(1,2) & scenetype == 1, 
                        select = c("num_of_species", "species", "pos", "scenetype", "height_m", "abs_mean"))

ggplot(data = sp_of_interest, 
       aes(x = height_m, y = abs_mean, col = interaction(num_of_species, species), group = interaction(pos, species))) +
  geom_line(size = 1) +
  ylab("FAPAR")  + theme_bw() + xlab("height, m") + 
  scale_color_brewer(palette = "Paired",direction=-1, name = NULL, labels = c("beech in monoculture", "beech in mixture", "elm in monoculture", "elm in mixture")) +
  coord_flip() + theme(legend.position = c(0.555, 0.17), legend.key = element_rect(colour = "transparent", fill = "transparent"),
                       legend.box.background = element_rect(fill = "transparent")) +
  scale_y_continuous(breaks = seq(0,0.14,0.05)) +
  myprettyoptions
```



```{r fig.height=7, fig.width=12}
subdat = read_profiles(trait = "lop")
sp_of_interest = subset(subdat, height_m != 1 & num_of_species %in% c(1,2), select = c("num_of_species", "species", "pos", "scenetype", "height_m", "abs_mean"))


sp_of_interest$scenetype = as.factor(sp_of_interest$scenetype)
levels(sp_of_interest$scenetype) = c("white", "black", "natural")


whbl_subdat = merge(sp_of_interest[sp_of_interest$scenetype == "white",], 
                    sp_of_interest[sp_of_interest$scenetype == "black",], 
                      by = c("num_of_species", "species", "pos", "height_m"))
whbl_subdat$abs_mean = whbl_subdat$abs_mean.x - whbl_subdat$abs_mean.y
whbl_subdat$scenetype = "white - black"
whbl_subdat = subset(whbl_subdat, select = c("num_of_species", "species", "pos", "scenetype", "height_m", "abs_mean"))

sp_of_interest = as.data.frame(rbind(sp_of_interest, whbl_subdat))
sp_of_interest$scenetype = factor(sp_of_interest$scenetype,c("white", "black", "white - black", "natural"))
mix_tab = diff_betw_sp_in_mix_and_in_mon(sp_of_interest)

```

```{r fig.height=4, fig.width=2.1}
#mix_tab = diff_betw_sp_in_mix_and_in_mon(sp_of_interest)
ggplot(data = subset(mix_tab, scenetype == "white"), 
       aes(x = pos, y = abs_mean, col = as.factor(species), group = as.factor(pos))) +
  geom_point(size = 2) + geom_hline(aes(yintercept = 0), col = "gray8") + geom_segment(aes(x=pos, xend=pos, y=0, yend=abs_mean )) +
  ylab("FAPAR gain")  + theme_bw() + xlab("mixtures of two species") + 
  coord_flip() +
  scale_color_brewer(palette = "Dark2", name = "") +
  #geom_point(aes(x = pos, y = gain_mix, col = "z"), size = 2) +
  scale_y_continuous(breaks = seq(-1,0.15,0.05)) +
  scale_x_continuous(breaks = c(0)) +
  myprettyoptions +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(), legend.position = "none")
```



### Difference in absorptance

```{r fig.height=8, fig.width=14}
mix_tab = diff_betw_sp_in_mix_and_in_mon(sp_of_interest)
ggplot(data = mix_tab, 
       aes(x = pos, y = abs_mean, col = as.factor(species), group = as.factor(pos))) +
  geom_point(size = 2.5) + geom_hline(aes(yintercept = 0), col = "gray8") + geom_segment(aes(x=pos, xend=pos, y=0, yend=abs_mean )) +
  ylab("difference in mixtures minus monocultures")  + theme_bw() + xlab("different mixtures") + 
  ggtitle("type of background") + 
  #scale_color_viridis(option="inferno") +
  coord_flip() +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_y_continuous(breaks = seq(-1,0.15,0.05)) +
  #scale_y_continuous(breaks = seq(-1,1,0.2)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_blank(),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=3, fig.width=8, message=TRUE, warning=TRUE}
lops_fapar = subset(dart_lops,type %in% c("transm", "refl") & wavelength >= 400 & wavelength <= 700)
ggplot(data = lops_fapar, 
       aes(x = wavelength, y = value, col = species, group = interaction(species, type))) +
  geom_line(size = 1) +
  ylab("proportion of light")  + theme_bw() + xlab("wavelength") + 
  scale_color_brewer(palette="Dark2") +
  #facet_wrap(~type, ncol = 1) +
  facet_grid(rows = vars(type)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r}
lops_fapar = subset(dart_lops,type %in% c("transm", "refl") & wavelength %in% c(400, 500, 600, 700))
lops_fapar = aggregate(value ~ species + type, data = lops_fapar, FUN = "mean")
lops_fapar_refl = lops_fapar[lops_fapar$type == "refl",]
lops_fapar_transm = lops_fapar[lops_fapar$type == "transm",]
mix_tab$refl = lops_fapar_refl$value[match(mix_tab$species, lops_fapar_refl$species)]
mix_tab$transm = lops_fapar_transm$value[match(mix_tab$species, lops_fapar_transm$species)]
```

```{r fig.height=7, fig.width=5}
ggplot(data = subset(mix_tab, scenetype == "white"), 
       aes(x = diff_mon*transm, y = abs_mean, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("abs_mean")  + theme_bw() + xlab("Transmittance") + 
  scale_color_brewer(palette = "Dark2", name = NULL) +
  scale_x_continuous(breaks = seq(-1,1,0.02)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=7, fig.width=12}
ggplot(data = mix_tab, 
       aes(x = diff_mon, y = diff_mix, col = as.factor(name_species), group = as.factor(pos)) ) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("abs_ab_a - abs_ab_b")  + theme_bw() + xlab("Difference in absorptance of monocultures") + 
  ggtitle("type of background") + 
  #coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_x_continuous(breaks = seq(-1,1,0.1)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```
```{r fig.height=5, fig.width=10}
ab_mixtab = mix_tab
ab_mixtab$diff_mon[ab_mixtab$sp_a == 0] = - ab_mixtab$diff_mon[ab_mixtab$sp_a == 0]
ggplot(data = ab_mixtab, 
       aes(x = diff_mon, y = abs_mean, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point(size = 1.5) + #geom_line() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("surplus in FAPAR")  + theme_bw() + xlab("Difference in absorptance of monocultures") + 
  ggtitle("type of background") + 
  #coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_x_continuous(breaks = seq(-1,1,0.1)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=4, fig.width=2.3}
ab_mixtab = mix_tab
ab_mixtab$diff_mon[ab_mixtab$sp_a == 0] = - ab_mixtab$diff_mon[ab_mixtab$sp_a == 0]
ab_mixtab = ab_mixtab[ab_mixtab$scenetype == "white",]
ggplot(data = ab_mixtab, 
       aes(x = diff_mon, y = abs_mean, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point(size = 1.5) + #geom_line() +
  scale_color_brewer(palette = "Dark2", name = "") +
  ylab("FAPAR gain")  + theme_bw() + xlab("FAPAR difference\n in monocultures") + 
  scale_x_continuous(breaks = seq(-1,1,0.2)) +
  myprettyoptions + theme(panel.grid.minor.y = element_blank(), legend.position = "none")
```


```{r fig.height=4, fig.width=6.9}
ab_mixtab = mix_tab
ab_mixtab$diff_mon[ab_mixtab$sp_a == 0] = - ab_mixtab$diff_mon[ab_mixtab$sp_a == 0]
ab_mixtab = ab_mixtab[ab_mixtab$scenetype == "white",]
ggplot(data = ab_mixtab, 
       aes(x = diff_mon, y = abs_mean, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point(size = 1.5) + #geom_line() +
  scale_color_brewer(palette = "Dark2", guide = 
                       guide_legend(title = "LOP", nrow = 1)) + 
  ylab("surplus in FAPAR")  + theme_bw() + xlab("FAPAR difference\n in monocultures") + 
  scale_x_continuous(breaks = seq(-1,1,0.2)) +
  myprettyoptions + theme(panel.grid.minor.y = element_blank(), legend.position = "bottom")
```


```{r fig.height=7, fig.width=13}

ggplot(data = ab_mixtab, 
       aes(x = abs(diff_mix*diff_mon), y = gain_mix, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point() + geom_line() +
    #aes(x = 0.5*mon_abs*diff_mon, y = abs_mean, group = as.factor(scenetype)), method = "lm" ) +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("gain_a")  + theme_bw() + xlab("abs_a - abs_b") + 
  ggtitle("type of background") + 
  #coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_x_continuous(breaks = seq(-1,1,0.05)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r fig.height=7, fig.width=13}

ggplot(data = ab_mixtab, 
       aes(x = mon_abs*diff_mon, y = diff_mix, col = as.factor(species), group = as.factor(pos)) ) +
  geom_point() +
  #geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("diff_mix")  + theme_bw() + xlab("abs_a*(abs_a - abs_b)") + 
  ggtitle("type of background") + 
  #coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_x_continuous(breaks = seq(-1,1,0.1)) +

  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```

```{r}
head(mix_tab)
mix_tab$sp_a = sapply(c(1:nrow(mix_tab)), function(x) ifelse(mix_tab$mon_abs[i] > mix_tab$mon_abs[i+1], 1, 0))
```


```{r fig.height=8, fig.width=14}
ggplot(data = mix_tab, 
       aes(x = mon_abs, y = abs_mean, col = as.factor(name_species), group = as.factor(pos)) ) +
  geom_point() + geom_line() +
  geom_hline(aes(yintercept = 0), col = "gray35") +
  ylab("rence in mixtures minus monocultures")  + theme_bw() + xlab("absorptance in monoculture") + 
  ggtitle("type of background") + 
  coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_y_continuous(breaks = seq(-1,0.15,0.05)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(), 
        #panel.grid.major.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))
```
```{r}
head(mix_tab)
```

```{r}
tab_scene = subset(mix_tab, scenetype == "white")
cor.test(tab_scene$diff_mon, tab_scene$diff_mix)
```

```{r}
tab_scene = subset(mix_tab, scenetype == "white")
cor.test(tab_scene$abs_mean, tab_scene$mon_abs)
```


```{r fig.height=7, fig.width=12}
subdat = read_profiles(trait = "lop")
mix_tab = diff_betw_mix_and_av_of_mon(subdat)

ggplot(data = mix_tab, 
       aes(x = height_m, y = abs_mean, col = diff_sum, group = as.factor(pos))) +
  geom_line(size = 1) +
  ylab("proportion of absorbed light")  + theme_bw() + xlab("height, m") + 
  ggtitle("type of background") + 
  scale_color_viridis(option="inferno") +
  coord_flip() +
  facet_grid(~scenetype, space = "free", scales = "free") + 
  scale_y_continuous(breaks = seq(0,0.15,0.002)) +
  theme(panel.grid.major = element_line(colour = "lightgrey"), panel.grid.minor.y = element_blank(),
        plot.title = element_text(size=16, hjust = 0.5),
        axis.title.x = element_text(size=16), axis.text.x  = element_text(size=12),
        axis.title.y = element_text(size=16), axis.text.y  = element_text(size=12),
        strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14),
        legend.text = element_text(size=12), legend.title = element_text(size=14), title = element_text(size=16))

```
